spring:
  application:
    name: filter-admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/filter?characterEncoding=utf8
    username: root
    password: xxxx

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    root: info
  config: classpath:log4j2.xml

degrade:
  areaList: true